Changed everything to english and uniformize indentation

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -2,7 +2,7 @@
 
 shopt -s nullglob
 
-# script de test pour le projet de compilation
+# testing script for the compilation project
 
 option=$1
 compilo=$2
@@ -11,64 +11,64 @@ max=0
 verbose=0
 
 
-echo "Test de $2"
+echo "Test for $compilo"
 
 echo
 
-# tous les tests passent avec gcc
+# every test is done with gcc
 test_gcc() {
 for f in syntax/bad/*.c; do
     if gcc -c $f > /dev/null 2>&1 ; then
-      echo "succès de gcc -c sur $f"; exit 1
+        echo "success of gcc -c on $f"; exit 1
     fi
 done
 
 for f in typing/good/*.c exec/*.c exec-fail/*.c; do
     gcc -c $f > /dev/null 2>&1 ||
-     (echo "echec de gcc sur $f"; exit 1)
+    (echo "failure of gcc on $f"; exit 1)
 done
 for f in typing/bad/*.c; do
     if gcc -c $f > /dev/null 2>&1 ; then
-      echo "succès de gcc -c sur $f"; exit 1
+        echo "success of gcc -c on $f"; exit 1
     fi
 done
 for f in exec/*.c; do
     if test $f == exec/sizeof1.c; then continue; fi
     if test $f == exec/sizeof2.c; then continue; fi
-    echo "test gcc sur $f"
+    echo "test gcc on $f"
     expected=exec/`basename $f .c`.out
     if gcc $f > /dev/null 2>&1 ; then
-      ./a.out > out
-      if ! cmp --quiet out $expected; then
-          echo "mauvaise sortie de gcc sur $f"; exit 1
-      fi
+        ./a.out > out
+        if ! cmp --quiet out $expected; then
+            echo "wrong output of gcc on $f"; exit 1
+        fi
     else
-      echo "échec de gcc -c sur $f"; exit 1
+        echo "failure of gcc -c on $f"; exit 1
     fi
 done
 }
 
 compile () {
 if [[ $verbose != 0 ]]; then
-  echo Compile $1 $2
-  $compilo $1 $2;
+    echo Compile $1 $2
+    $compilo $1 $2;
 else
-  $compilo $1 $2 > /dev/null 2>&1;
+    $compilo $1 $2 > /dev/null 2>&1;
 fi;
 }
 
 
-# partie 1 : tests d'analyse syntaxique
+# Part 1: syntactic analysis tests
 
-partie1 () {
+part1 () {
 
 score=0
 max=0
 
-echo "Partie 1"
+echo "Part 1"
 
-# les mauvais
-echo -n "mauvais "
+# bad ones
+echo -n "bad "
 for f in syntax/bad/*.c; do
     echo -n ".";
     max=`expr $max + 1`;
@@ -76,17 +76,17 @@ for f in syntax/bad/*.c; do
     case $? in
 	"0")
 	echo
-	echo "ECHEC sur "$f" (devrait échouer)";;
+	echo "FAILURE on "$f" (should fail)";;
 	"1") score=`expr $score + 1`;;
 	*)
 	echo
-	echo "ECHEC sur "$f" (pour une mauvaise raison)";;
+	echo "FAILURE on "$f" (for a wrong reason)";;
     esac
 done
 echo
 
-# les bons
-echo -n "bons "
+# good ones
+echo -n "good "
 for f in syntax/good/*.c typing/bad/*.c typing/good/*.c exec/*.c exec-fail/*.c; do
     echo -n ".";
     max=`expr $max + 1`;
@@ -94,31 +94,30 @@ for f in syntax/good/*.c typing/bad/*.c typing/good/*.c exec/*.c exec-fail/*.c; 
     case $? in
 	"1")
 	echo
-	echo "ECHEC sur "$f" (devrait reussir)";;
+	echo "FAILURE on "$f" (should succeed)";;
 	"0") score=`expr $score + 1`;;
 	*)
 	echo
-	echo "ECHEC sur "$f" (pour une mauvaise raison)";;
+	echo "FAILURE on "$f" (for a wrong reason)";;
     esac
 done
 echo
 
 percent=`expr 100 \* $score / $max`;
 
-echo -n "Syntaxe : $score/$max : $percent%"; }
+echo -n "Syntax: $score/$max : $percent%"; }
 
-# partie 2 : tests d'analyse sémantique
+# Part 2: semantic analysis tests
 
-
-partie2 () {
+part2 () {
 echo
-echo "Partie 2"
+echo "Part 2"
 
 score=0
 max=0
 
-# les mauvais
-echo -n "mauvais "
+# bad ones
+echo -n "bad "
 for f in typing/bad/*.c; do
     echo -n ".";
     max=`expr $max + 1`;
@@ -126,17 +125,17 @@ for f in typing/bad/*.c; do
     case $? in
 	"0")
 	echo
-	echo "ECHEC sur "$f" (devrait échouer)";;
+	echo "FAILURE on "$f" (should fail)";;
 	"1") score=`expr $score + 1`;;
 	*)
 	echo
-	echo "ECHEC sur "$f" (pour une mauvaise raison)";;
+	echo "FAILURE on "$f" (for a wrong reason)";;
     esac
 done
 echo
 
-# les bons
-echo -n "bons "
+# good ones
+echo -n "good "
 for f in typing/good/*.c exec/*.c exec-fail/*.c; do
     echo -n ".";
     max=`expr $max + 1`;
@@ -144,11 +143,11 @@ for f in typing/good/*.c exec/*.c exec-fail/*.c; do
     case $? in
 	"1")
 	echo
-	echo "ECHEC sur "$f" (devrait reussir)";;
+	echo "FAILURE on "$f" (should succeed)";;
 	"0") score=`expr $score + 1`;;
 	*)
 	echo
-	echo "ECHEC sur "$f" (pour une mauvaise raison)";;
+	echo "FAILURE on "$f" (for a wrong reason)";;
     esac
 done
 echo
@@ -159,17 +158,17 @@ echo    "Typage  : $score/$max : $percent%";
 }
 
 
-# partie 3 : tests d'interprétation
+# Part 3: interpretation tests
 
-partie3i () {
+part3i () {
 
 score_comp=0
 score_test=0
 max=0
 
 echo
-echo "Interprétation"
-echo "Execution normale"
+echo "Interpretation"
+echo "Normal execution"
 echo "-----------------"
 
 # timeout="why3-cpulimit 30 0 -h"
@@ -185,16 +184,16 @@ for f in exec/*.c; do
 	    score_test=`expr $score_test + 1`
 	else
 	    echo
-	    echo "ECHEC : mauvaise sortie pour $f"
+	    echo "FAILURE: wrong output for $f"
 	fi
     else
 	echo
-	echo "ECHEC du compilateur sur $f (devrait réussir)"
+	echo "FAILURE of the compiler on $f (should succeed)"
     fi
 done
 echo
 
-echo "Execution conduisant à un échec"
+echo "Execution leading to a failure"
 echo "-------------------------------"
 
 for f in exec-fail/*.c; do
@@ -202,7 +201,7 @@ for f in exec-fail/*.c; do
     max=`expr $max + 1`;
     if $compilo $f > /dev/null 2>&1; then
         echo
-	echo "ECHEC : le code $f devrait échouer"
+	echo "FAILURE: the code $f should fail"
     else
 	score_test=`expr $score_test + 1`;
 	score_comp=`expr $score_comp + 1`;
@@ -214,11 +213,11 @@ percent=`expr 100 \* $score / $max`;
 
 echo "Compilation:";
 percent=`expr 100 \* $score_comp / $max`;
-echo "Compilation : $score_comp/$max : $percent%";
+echo "Compilation: $score_comp/$max : $percent%";
 percent=`expr 100 \* $score_test / $max`;
-echo "Comportement du code : $score_test/$max : $percent%";}
+echo "Code behavior: $score_test/$max : $percent%";}
 
-partie3 () {
+part3 () {
 
 score_comp=0
 score_out=0
@@ -226,8 +225,8 @@ score_test=0
 max=0
 
 echo
-echo "Partie 3"
-echo "Execution normale"
+echo "Part 3"
+echo "Normal execution"
 echo "-----------------"
 
 # timeout="why3-cpulimit 30 0 -h"
@@ -247,20 +246,20 @@ for f in exec/*.c; do
 		score_test=`expr $score_test + 1`;
 	    else
 		echo
-		echo "ECHEC : mauvaise sortie pour $f"
+		echo "FAILURE: wrong output for $f"
 	    fi
 	else
 		echo
-		echo "ECHEC du code produit pour $f"
+		echo "FAILURE of the produced code for $f"
 	fi
     else
 	echo
-	echo "ECHEC de la compilation sur $f (devrait réussir)"
+	echo "FAILURE of the compiler on $f (should succeed)"
     fi
 done
 echo
 
-echo "Execution conduisant à un échec"
+echo "Execution leading to a failure"
 echo "-------------------------------"
 
 for f in exec-fail/*.c; do
@@ -272,14 +271,14 @@ for f in exec-fail/*.c; do
 	score_comp=`expr $score_comp + 1`;
 	if ./a.out > out; then
 	    echo
-	    echo "ECHEC : le code $f devrait échouer"
+	    echo "FAILURE: the code $f should fail"
 	else
 	    score_test=`expr $score_test + 1`;
 	    score_out=`expr $score_out + 1`;
 	fi
     else
 	echo
-	echo "ECHEC de la compilation sur $f (devrait réussir)"
+	echo "FAILURE of the compiler on $f (should succeed)"
     fi
 done
 
@@ -288,47 +287,47 @@ percent=`expr 100 \* $score / $max`;
 
 echo "Compilation:";
 percent=`expr 100 \* $score_comp / $max`;
-echo "Compilation : $score_comp/$max : $percent%";
+echo "Compilation: $score_comp/$max : $percent%";
 percent=`expr 100 \* $score_out / $max`;
-echo "Code produit : $score_out/$max : $percent%";
+echo "Produced code: $score_out/$max : $percent%";
 percent=`expr 100 \* $score_test / $max`;
-echo "Comportement du code : $score_test/$max : $percent%";}
+echo "Code behavior: $score_test/$max : $percent%";}
 
 
 case $option in
     "-1" )
-        partie1;;
+        part1;;
     "-2" )
-        partie2;;
+        part2;;
     "-i" )
-        partie3i;;
+        part3i;;
     "-3" )
-        partie3;;
+        part3;;
     "-v1" )
 	verbose=1;
-	partie1;;
+	part1;;
     "-v2" )
     	verbose=1;
-        partie2;;
+        part2;;
     "-v3" )
     	verbose=1;
-        partie3;;
+        part3;;
     "-all" )
-    	partie1;
-    	partie2;
-    	partie3;;
+    	part1;
+    	part2;
+    	part3;;
     "-gcc" )
         test_gcc;;
     * )
-        echo "usage : $0 <option> <compilo>"
-        echo "spécifier une option parmi : "
-        echo "-1      : tester l'analyse syntaxique"
-        echo "-2      : tester le typage"
-        echo "-3      : tester la compilation"
-        echo "-v1     : tester l'analyse syntaxique (verbeusement)"
-        echo "-v2     : tester le typage (verbeusement)"
-        echo "-v3     : tester la compilation (verbeusement)"
-        echo "-all    : tout tester";;
+        echo "usage: $0 <option> <compilo>"
+        echo "specify an option among: "
+        echo "-1  : test the syntactic analysis"
+        echo "-2  : test the typing"
+        echo "-3  : test the compilation"
+        echo "-v1 : test syntactic analysis (verbosely)"
+        echo "-v2 : test le typage (verbosely)"
+        echo "-v3 : test the compilation (verbosely)"
+        echo "-all: test everything";;
 
 esac
 echo
